project_id = "ddibbbbzcdlnkgymizbg"

[functions.low-stock-alert]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.serve-quote]
verify_jwt = false

[functions.draft-recovery]
verify_jwt = false

[functions.ai-auditor]
verify_jwt = false
